name: Go Build And Deploy to AWS Lambda
env:
  APP_NAME: 'AWS Lambda Deployment'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
      - main
    paths:
      - 'devops/aws-lambda-deployment/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Create .env file
        run: |
          echo "APP_NAME=${{ env.APP_NAME }}" >>  devops/aws-lambda-deployment/cmd/.env
          # Add more environment variables as needed

      - name: Build the Go application
        run: |
          cd devops/aws-lambda-deployment/cmd && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o bootstrap *.go && zip deployment.zip .env bootstrap

      - name: Upload to AWS Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-southeast-1  
          function_name: go_staging
          runtime: go1.x
          zip_file: devops/aws-lambda-deployment/cmd/deployment.zip